#!/bin/sh

export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:$HOME/bin"
export TERM=screen-256color

export EDITOR=nvim
export VISUAL=nvim
export PAGER=less

# Use local virtualenv rather than global site packages.
source ~/.pythonenv/bin/activate
