#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         1
bspc config bottom_padding       14
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color '#9D9B9E'
bspc config active_border_color '#005F87'
bspc config focused_border_color '#005F87'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Screenkey manage=off

# Make all windows floating by default, excluding
# the first workspace.
#TILING_DESK_ID=$(bspc query -D -d '^1')
#
#bspc subscribe node_manage | while read -a MSG; do
#  DESK_ID=${MSG[2]}
#  WID=${MSG[3]}
#  [ "$TILING_DESK_ID" -ne "$DESK_ID" ] && bspc node "$WID" -t floating
#done &
