#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         1
bspc config bottom_padding       13
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color '#3b3b3b'
bspc config active_border_color '#d8ad4c'
bspc config focused_border_color '#d8ad4c'

bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Screenkey manage=off

TILING_DESK_ID=$(bspc query -D -d '^8')

bspc subscribe node_manage | while read -a MSG; do
  DESK_ID=${MSG[2]}
  WID=${MSG[3]}
  [ "$TILING_DESK_ID" = "$DESK_ID" ] && bspc node "$WID" -t floating
done &
