#!/bin/zsh

source $HOME/scripts/extractcol

# Fonts
FONT1="siji"
FONT2="boxxy"


# Panel 
PW=300
PH=48
PX=533
PY=372

echo "%{c}%{F$BLUE} %{F$FG}%{A:p:}Shutdown%{A}  %{A:r:}Reboot%{A}  %{A:s:}Suspend%{A}  %{A:b:}Exit%{A}  " | lemonbar -g ${PW}x${PH}+${PX}+${PY} -f "$FONT1" -f "$FONT2" -B "$BG" -F "$FG" -dp | \
    while :; do
        read line
        case $line in 
            'b')
                p=$(pgrep -n lemonbar)
                kill $p 
                exit 
                ;;
            's')
                /usr/sbin/pm-suspend &
                p=$(pgrep -n lemonbar)
                kill $p 
                exit                
                ;;
            'p')
                poweroff
                exit
                ;;
            'r')
                /sbin/shutdown -r now
                exit
                ;;
        esac
    done

